# application.properties

server.port=8080

# ====================================================
# ACTIVE: AWS RDS MySQL (Live Cloud Database)
# ====================================================
spring.datasource.url=jdbc:mysql://database-1.cql86o6qoghp.us-east-1.rds.amazonaws.com:3306/catalogdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin1
# !! ENTER YOUR RDS PASSWORD ON THE LINE BELOW !!
spring.datasource.password=CloudPass123!

# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS Config (For React Frontend)
app.cors.allowedOrigins=http://localhost:5173,http://localhost:3000
